version: '3.9'

services:
  mysql_server:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: mysql:${MYSQL_TAG}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: public
      MYSQL_DATABASE: mqtt
      MYSQL_USER: emqx
      MYSQL_PASSWORD: public
    ports:
      - "${MAP_PORT}:3306"
    volumes:
      - ../../apps/emqx_auth_mysql/test/emqx_auth_mysql_SUITE_data/init-db-tcp.txt:/etc/mysql-init-db.txt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - emqx_bridge
    command:
      --bind-address "::"
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --skip-symbolic-links
    healthcheck:
      test: " mysql -uemqx -ppublic -e 'use mqtt;'"
      interval: 5s
      timeout: 5s
      retries: 20


networks:
  emqx_bridge:
    driver: bridge
    name: emqx_bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.100.239.0/24
          gateway: 172.100.239.1
        - subnet: 2001:3200:3200::/64
          gateway: 2001:3200:3200::1
